-- Create Snowpipe for Employee salary Data
CREATE OR REPLACE PIPE USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_SALARY_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_SALARY_DATA
FROM @USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_SALARY_STAGE;