CREATE OR REPLACE PROCEDURE USER_DB_DEV.EMPLOYEE_DATA.CalculateBonusPercentage()
RETURNS TABLE (
    EMPLOYEE_FULL_NAME VARCHAR,
    BONUS_PERCENTAGE DECIMAL(5, 2)
)
LANGUAGE SQL
AS
$$
    SELECT EN.EMPLOYEE_FULL_NAME,
           (EN.BONUS / EN.ANNUAL_SALARY) * 100 AS BONUS_PERCENTAGE
    FROM USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_NAME_DATA EN;
$$;
