-- Create Snowpipe for Employee Name Data
CREATE OR REPLACE PIPE USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_NAME_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_NAME_DATA
FROM @USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_NAME_STAGE;