CREATE OR REPLACE PROCEDURE USER_DB_DEV.EMPLOYEE_DATA.GetEmployeeAgeRange()
RETURNS TABLE (
    AGE_RANGE VARCHAR,
    EMPLOYEE_COUNT INTEGER
)
LANGUAGE SQL
AS
$$
    SELECT CASE
               WHEN EA.AGE BETWEEN '18' AND '30' THEN '18-30'
               WHEN EA.AGE BETWEEN '31' AND '45' THEN '31-45'
               WHEN EA.AGE BETWEEN '46' AND '60' THEN '46-60'
               ELSE '60+'
           END AS AGE_RANGE,
           COUNT(*) AS EMPLOYEE_COUNT
    FROM USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_AGE_DATA EA
    GROUP BY AGE_RANGE
    ORDER BY AGE_RANGE;
$$;
