CREATE OR REPLACE PROCEDURE USER_DB_DEV.EMPLOYEE_DATA.GetEmployeeDetailsWithAttributes()
RETURNS TABLE (
    EEID VARCHAR,
    COUNTRY VARCHAR,
    CITY VARCHAR,
    ANNUAL_SALARY DECIMAL(10, 2),
    BONUS DECIMAL(5, 2),
    AGE VARCHAR,
    EMPLOYEE_FULL_NAME VARCHAR,
    GENDER VARCHAR,
    ETHNICITY VARCHAR
)
LANGUAGE SQL
AS
$$
    SELECT EL.EEID, EL.COUNTRY, EL.CITY, EN.ANNUAL_SALARY, EN.BONUS,
           EA.AGE, EN.EMPLOYEE_FULL_NAME, EN.GENDER, EN.ETHNICITY
    FROM USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_LOCATION_DATA EL
    JOIN USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_NAME_DATA EN ON EL.EEID = EN.EEID
    JOIN USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_AGE_DATA EA ON EL.EEID = EA.FULL_NAME;
$$;
