CREATE OR REPLACE PROCEDURE USER_DB_DEV.EMPLOYEE_DATA.GetEmployeeDepartmentChangeHistory(
    in_eeid VARCHAR
)
RETURNS TABLE (
    DEPARTMENT VARCHAR,
    CHANGE_DATE DATE
)
LANGUAGE SQL
AS
$$
    SELECT DEPARTMENT, CHANGE_DATE
    FROM (
        SELECT DEPARTMENT, HIRE_DATE AS CHANGE_DATE FROM USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_DEPARTMENT_DATA WHERE EEID = in_eeid
        UNION ALL
        SELECT DEPARTMENT, EXIT_DATE AS CHANGE_DATE FROM USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_JOB_DATA WHERE EEID = in_eeid
    )
    ORDER BY CHANGE_DATE;
$$;
