CREATE OR REPLACE PROCEDURE USER_DB_DEV.EMPLOYEE_DATA.GetEmployeeCountByEthnicity()
RETURNS TABLE (
    ETHNICITY VARCHAR,
    EMPLOYEE_COUNT INTEGER
)
LANGUAGE SQL
AS
$$
    SELECT EN.ETHNICITY,
           COUNT(*) AS EMPLOYEE_COUNT
    FROM USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_NAME_DATA EN
    GROUP BY EN.ETHNICITY;
$$;
