-- GRANT SECURITY AND FUTURE ACCESS
GRANT ALL ON SCHEMA USER_DB_DEV.EMPLOYEE_DATA TO ROLE PRIMARY_ROLE;

GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA USER_DB_DEV.EMPLOYEE_DATA TO ROLE PRIMARY_ROLE;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA USER_DB_DEV.EMPLOYEE_DATA TO ROLE PRIMARY_ROLE;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA USER_DB_DEV.EMPLOYEE_DATA TO ROLE PRIMARY_ROLE;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA USER_DB_DEV.EMPLOYEE_DATA TO ROLE PRIMARY_ROLE;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA USER_DB_DEV.EMPLOYEE_DATA TO ROLE PRIMARY_ROLE;
GRANT OWNERSHIP ON FUTURE PIPES IN SCHEMA USER_DB_DEV.EMPLOYEE_DATA TO ROLE PRIMARY_ROLE;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA USER_DB_DEV.EMPLOYEE_DATA TO ROLE PRIMARY_ROLE;

GRANT USAGE ON DATABASE USER_DB_DEV TO ROLE PRIMARY_ROLE;
GRANT USAGE ON SCHEMA USER_DB_DEV.EMPLOYEE_DATA TO ROLE PRIMARY_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA USER_DB_DEV.EMPLOYEE_DATA TO ROLE PRIMARY_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA USER_DB_DEV.EMPLOYEE_DATA TO ROLE PRIMARY_ROLE;

-- Grant privileges to the schema (example: usage, create privileges on the schema itself)
GRANT USAGE, CREATE ON SCHEMA EMPLOYEE_DATA TO PRIMARY_ROLE;

-- Assign the role to the user
GRANT PRIMARY_ROLE TO USER USER_1;