CREATE OR REPLACE PROCEDURE USER_DB_DEV.EMPLOYEE_DATA.GetEmployeeDepartmentAndJobHistory(
    in_eeid VARCHAR
)
RETURNS TABLE (
    DEPARTMENT VARCHAR,
    BUSINESS_UNIT VARCHAR,
    JOB_TITLE VARCHAR,
    HIRE_DATE DATE,
    EXIT_DATE DATE
)
LANGUAGE SQL
AS
$$
    SELECT ED.DEPARTMENT, ED.BUSINESS_UNIT, EJ.JOB_TITLE, EJ.HIRE_DATE, EJ.EXIT_DATE
    FROM USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_DEPARTMENT_DATA ED
    JOIN USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_JOB_DATA EJ ON ED.EEID = EJ.EEID
    WHERE ED.EEID = in_eeid;
$$;
