CREATE OR REPLACE PROCEDURE USER_DB_DEV.EMPLOYEE_DATA.GetEmployeeNameAgeByCity(
    in_city VARCHAR
)
RETURNS TABLE (
    EMPLOYEE_FULL_NAME VARCHAR,
    AGE VARCHAR
)
LANGUAGE SQL
AS
$$
    SELECT EN.EMPLOYEE_FULL_NAME, EA.AGE
    FROM USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_NAME_DATA EN
    JOIN USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_AGE_DATA EA ON EN.EEID = EA.FULL_NAME
    JOIN USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_LOCATION_DATA EL ON EN.EEID = EL.EEID
    WHERE EL.CITY = in_city;
$$;
