-- Create procedure
CREATE OR REPLACE PROCEDURE USER_DB_DEV.EMPLOYEE_DATA.GetTopEarnersByCountry()
RETURNS TABLE (
    COUNTRY VARCHAR,
    EMPLOYEE_FULL_NAME VARCHAR,
    TOTAL_COMPENSATION DECIMAL(15, 2),
    RANK INTEGER
)
LANGUAGE SQL
AS
$$
    WITH RankedEmployees AS (
        SELECT EL.COUNTRY,
               EN.EMPLOYEE_FULL_NAME,
               EN.ANNUAL_SALARY + EN.BONUS AS TOTAL_COMPENSATION,
               RANK() OVER (PARTITION BY EL.COUNTRY ORDER BY EN.ANNUAL_SALARY + EN.BONUS DESC) AS RANK
        FROM USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_LOCATION_DATA EL
        JOIN USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_NAME_DATA EN ON EL.EEID = EN.EEID
    )
    SELECT COUNTRY, EMPLOYEE_FULL_NAME, TOTAL_COMPENSATION, RANK
    FROM RankedEmployees
    WHERE RANK = 1;
$$;


