CREATE OR REPLACE PROCEDURE USER_DB_DEV.EMPLOYEE_DATA.GetTotalSalaryBonusByCountry()
RETURNS TABLE (
    COUNTRY VARCHAR,
    TOTAL_SALARY DECIMAL(15, 2),
    TOTAL_BONUS DECIMAL(10, 2)
)
LANGUAGE SQL
AS
$$
    SELECT EL.COUNTRY,
           SUM(EN.ANNUAL_SALARY) AS TOTAL_SALARY,
           SUM(EN.BONUS) AS TOTAL_BONUS
    FROM USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_LOCATION_DATA EL
    JOIN USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_NAME_DATA EN ON EL.EEID = EN.EEID
    GROUP BY EL.COUNTRY;
$$;
