CREATE OR REPLACE PROCEDURE USER_DB_DEV.EMPLOYEE_DATA.GetEmployeesByHireDateRange(
    in_start_date DATE,
    in_end_date DATE
)
RETURNS TABLE (
    EEID VARCHAR,
    DEPARTMENT VARCHAR,
    BUSINESS_UNIT VARCHAR,
    JOB_TITLE VARCHAR
)
LANGUAGE SQL
AS
$$
    SELECT ED.EEID, ED.DEPARTMENT, ED.BUSINESS_UNIT, EJ.JOB_TITLE
    FROM USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_DEPARTMENT_DATA ED
    JOIN USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_JOB_DATA EJ ON ED.EEID = EJ.EEID
    WHERE EJ.HIRE_DATE BETWEEN in_start_date AND in_end_date;
$$;
