CREATE OR REPLACE PIPE USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_LOCATION_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_LOCATION_DATA
FROM @USER_DB_DEV.EMPLOYEE_DATA.EMPLOYEE_LOCATION_STAGE;